# Generated by Django 6.0 on 2026-02-20 01:14

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name='microservices-bucket', storage_name='default'
                ),
                upload_to='videos/',
            ),
        ),
    ]
