# Generated by Django 6.0 on 2026-03-11 22:36

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="zip_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="microservices-bucket", storage_name="default"
                ),
                upload_to="videos-processed/",
            ),
        ),
    ]
