from config.settings.main import DEBUG, INSTALLED_APPS, DATABASES, MIDDLEWARE, TEMPLATES, STATIC_URL, STATICFILES_DIRS

DEBUG = True


# HTTPS

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True

STORAGES = None
